name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: test
        run: >
          for manifest in */Cargo.toml; do
            cargo test --manifest-path="${manifest}" --verbose
          done
